# Generated by Django 4.2.2 on 2023-09-20 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemultisplit',
            old_name='gloscnosc',
            new_name='glosnosc',
        ),
        migrations.RenameField(
            model_name='devicesplit',
            old_name='gloscnosc',
            new_name='glosnosc',
        ),
    ]
