# Generated by Django 4.2.2 on 2023-09-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0002_rename_gloscnosc_devicemultisplit_glosnosc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemultisplit',
            old_name='klasa_energetyczna_chlodznie',
            new_name='klasa_energetyczna_chlodzenie',
        ),
        migrations.RenameField(
            model_name='devicesplit',
            old_name='klasa_energetyczna_chlodznie',
            new_name='klasa_energetyczna_chlodzenie',
        ),
    ]
