# Generated by Django 4.2.2 on 2023-09-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0003_rename_klasa_energetyczna_chlodznie_devicemultisplit_klasa_energetyczna_chlodzenie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspekcja',
            name='instalacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspekcje', to='klima.instalacja'),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='miejsce_agregatu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='miejsce_urzadzen_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='klima.photo'),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='podlaczenie_elektryki',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='prowadzenie_instalacji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='prowadzenie_skroplin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='device_multisplit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='device_split',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='gaz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='instalacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montaze', to='klima.instalacja'),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='miejsce_i_sposob_montazu_jedn_zew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='miejsce_montazu_jedn_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='miejsce_montazu_jedn_zew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='miejsce_montazu_jedn_zew_photo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='miejsce_podlaczenia_elektryki',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='miejsce_skroplin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='nr_seryjny_jedn_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='nr_seryjny_jedn_wew_photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='nr_seryjny_jedn_zew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='nr_seryjny_jedn_zew_photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='sposob_skroplin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='montaz',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='instalacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serwisy', to='klima.instalacja'),
        ),
    ]
