# Generated by Django 4.2.2 on 2023-09-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0004_alter_inspekcja_instalacja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serwis',
            name='czyszczenie_filtrow_jedn_wew',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='czyszczenie_obudowy_jedn_wew',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='czyszczenie_obudowy_jedn_zew',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='czyszczenie_tacy_skroplin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='czyszczenie_wymiennika_ciepla_wew',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='czyszczenie_wymiennika_ciepla_zew',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='data_montazu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='data_przegladu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='diagnostyka_awari',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='dlugosc_gwarancji',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='kontrola_droznosci_skroplin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='kontrola_poprawnosci_dzialania',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='kontrola_stanu_jedn_wew',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='kontrola_stanu_jedn_zew',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='kontrola_stanu_mocowania_agregatu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='kontrola_szczelnosci',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='kontrola_temperatury_nawiewu_wew',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='liczba_przegladow_rok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
