# Generated by Django 4.2.2 on 2023-09-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0005_serwis_czyszczenie_filtrow_jedn_wew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('offer_type', models.CharField(choices=[('split', 'Split'), ('multi_split', 'Multi Split')], max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klima.acuser')),
                ('devices_multi_split', models.ManyToManyField(blank=True, to='klima.devicemultisplit')),
                ('devices_split', models.ManyToManyField(blank=True, to='klima.devicesplit')),
                ('instalacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klima.instalacja')),
            ],
        ),
    ]
