# Generated by Django 4.2.2 on 2023-09-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0006_oferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemultisplit',
            old_name='kod_producenta',
            new_name='nazwa_modelu_producenta',
        ),
    ]
