# Generated by Django 4.2.2 on 2023-09-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0007_rename_kod_producenta_devicemultisplit_nazwa_modelu_producenta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rabat',
            old_name='brand',
            new_name='name',
        ),
    ]
