# Generated by Django 4.2.2 on 2023-09-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0008_rename_brand_rabat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='narzut',
            field=models.ManyToManyField(blank=True, to='klima.narzut'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='rabat',
            field=models.ManyToManyField(blank=True, to='klima.rabat'),
        ),
    ]
