# Generated by Django 4.2.2 on 2023-10-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0009_oferta_narzut_oferta_rabat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='miasto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='nazwa_firmy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='nip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='numer_telefonu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='ulica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
