# Generated by Django 4.2.2 on 2023-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0010_alter_userdata_kod_pocztowy_alter_userdata_miasto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Szablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('typ', models.CharField(choices=[('split', 'Split'), ('multisplit', 'Multisplit')], max_length=10)),
                ('devices_multisplit', models.ManyToManyField(blank=True, related_name='devices_multisplit', to='klima.devicemultisplit')),
                ('devices_split', models.ManyToManyField(blank=True, related_name='devices_split', to='klima.devicesplit')),
                ('narzuty', models.ManyToManyField(to='klima.narzut')),
                ('rabaty', models.ManyToManyField(to='klima.rabat')),
            ],
        ),
    ]
