# Generated by Django 4.2.2 on 2023-10-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0011_szablon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szablon',
            name='rabaty',
        ),
        migrations.AddField(
            model_name='szablon',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klima.acuser'),
            preserve_default=False,
        ),
    ]
