# Generated by Django 4.2.2 on 2023-10-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0012_remove_szablon_rabaty_szablon_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='mieszkanie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
