# Generated by Django 4.2.2 on 2023-10-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0013_userdata_mieszkanie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rabat',
            old_name='name',
            new_name='producent',
        ),
    ]
