# Generated by Django 4.2.2 on 2023-10-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0014_rename_name_rabat_producent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wykonane', 'Wykonane'), ('niewykonane', 'Niewykonane')], default='niewykonane', max_length=20)),
                ('nazwa', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('czy_oferta', models.BooleanField(default=False)),
                ('czy_faktura', models.BooleanField(default=False)),
                ('typ', models.CharField(choices=[('montaż', 'Montaż'), ('oględziny', 'Oględziny'), ('serwis', 'Serwis'), ('szkolenie', 'Szkolenie')], default='montaż', max_length=20)),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zadania', to='klima.group')),
                ('rodzic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zadania', to='klima.acuser')),
            ],
        ),
    ]
