# Generated by Django 4.2.2 on 2023-10-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0015_zadanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie',
            name='instalacja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zadania', to='klima.instalacja'),
        ),
        migrations.AlterField(
            model_name='zadanie',
            name='grupa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zadania', to='klima.group'),
        ),
    ]
