# Generated by Django 4.2.2 on 2023-11-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0016_zadanie_instalacja_alter_zadanie_grupa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narzut',
            options={'ordering': ['owner', 'order']},
        ),
        migrations.AddField(
            model_name='narzut',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
