# Generated by Django 4.2.2 on 2023-11-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0017_alter_narzut_options_narzut_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montaz',
            name='device_multisplit',
        ),
        migrations.RemoveField(
            model_name='montaz',
            name='device_split',
        ),
        migrations.AddField(
            model_name='montaz',
            name='devices_multi_split',
            field=models.ManyToManyField(blank=True, to='klima.devicemultisplit'),
        ),
        migrations.AddField(
            model_name='montaz',
            name='devices_split',
            field=models.ManyToManyField(blank=True, to='klima.devicesplit'),
        ),
    ]
