# Generated by Django 4.2.2 on 2023-11-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0018_remove_montaz_device_multisplit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.TextField(verbose_name='Stopka do faktury')),
                ('place_of_issue', models.CharField(max_length=255, verbose_name='Miejsce wystawienia faktury')),
                ('issuer_name', models.CharField(max_length=255, verbose_name='Imię i nazwisko osoby wystawiającej')),
                ('standard_payment_term', models.IntegerField(verbose_name='Standardowy termin płatności w dniach')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='Prefix')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='Sufiks')),
                ('numbering_type', models.CharField(choices=[('yearly', 'Od początku roku'), ('monthly', 'Od początku miesiąca'), ('daily', 'Liczone w danym dniu')], max_length=10, verbose_name='Rodzaj numeracji')),
                ('year_format', models.CharField(choices=[('YYYY', 'Czterocyfrowy'), ('YY', 'Dwucyfrowy')], max_length=4, verbose_name='Format roku')),
                ('month_format', models.CharField(choices=[('numeric', 'Liczbowy'), ('short_name', 'Skrócona nazwa'), ('full_name', 'Pełna nazwa')], max_length=10, verbose_name='Format miesiąca')),
                ('day_format', models.CharField(choices=[('numeric', 'Liczbowy'), ('two_digit', 'Zawsze dwucyfrowy')], max_length=10, verbose_name='Format dnia')),
                ('ac_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='klima.acuser')),
            ],
        ),
    ]
