# Generated by Django 4.2.2 on 2023-11-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0019_invoicesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='day_format',
            field=models.CharField(choices=[('numeric', 'Liczbowy'), ('two_digit', 'Zawsze dwucyfrowy')], max_length=10, null=True, verbose_name='Format dnia'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='footer',
            field=models.TextField(null=True, verbose_name='Stopka do faktury'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='issuer_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Imię i nazwisko osoby wystawiającej'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='month_format',
            field=models.CharField(choices=[('numeric', 'Liczbowy'), ('short_name', 'Skrócona nazwa'), ('full_name', 'Pełna nazwa')], max_length=10, null=True, verbose_name='Format miesiąca'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='numbering_type',
            field=models.CharField(choices=[('yearly', 'Od początku roku'), ('monthly', 'Od początku miesiąca'), ('daily', 'Liczone w danym dniu')], max_length=10, null=True, verbose_name='Rodzaj numeracji'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='place_of_issue',
            field=models.CharField(max_length=255, null=True, verbose_name='Miejsce wystawienia faktury'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='standard_payment_term',
            field=models.IntegerField(null=True, verbose_name='Standardowy termin płatności w dniach'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sufiks'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='year_format',
            field=models.CharField(choices=[('YYYY', 'Czterocyfrowy'), ('YY', 'Dwucyfrowy')], max_length=4, null=True, verbose_name='Format roku'),
        ),
    ]
