# Generated by Django 4.2.2 on 2023-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0020_alter_invoicesettings_day_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='iban',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='IBAN'),
        ),
    ]
