# Generated by Django 4.2.2 on 2023-11-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0021_invoicesettings_iban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faktury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Data wystawienia')),
                ('order', models.IntegerField(verbose_name='Kolejność')),
                ('ac_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_user', to='klima.acuser', verbose_name='Użytkownik wystawiający')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='klima.acuser', verbose_name='Klient')),
                ('instalacja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_instalacji_dla_faktury', to='klima.instalacja')),
            ],
        ),
    ]
