# Generated by Django 4.2.2 on 2023-11-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0022_faktury'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktury',
            name='id_fakturowni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Faktury w Fakturowni'),
        ),
    ]
