# Generated by Django 4.2.2 on 2023-11-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0023_faktury_id_fakturowni'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktury',
            name='numer_faktury',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer faktury'),
        ),
    ]
