# Generated by Django 4.2.2 on 2023-11-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0024_faktury_numer_faktury'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktury',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
    ]
