# Generated by Django 5.1.6 on 2025-04-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0025_faktury_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='client_status',
            field=models.CharField(choices=[('aktualny', 'Aktualny'), ('zakonczony', 'Zakończony')], default='Aktualny', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='numer_domu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='szablon',
            name='narzuty',
            field=models.ManyToManyField(blank=True, to='klima.narzut'),
        ),
    ]
