# Generated by Django 5.1.6 on 2025-04-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0026_userdata_client_status_userdata_numer_domu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='client_status',
            field=models.BooleanField(default=True),
        ),
    ]
