# Generated by Django 5.1.6 on 2025-04-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0028_alter_userdata_client_status_listaklientow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='client_status',
            field=models.CharField(choices=[('aktualny', 'Aktualny'), ('zakonczony', 'Zakończony')], default='0', max_length=20),
        ),
    ]
