# Generated by Django 5.1.6 on 2025-04-06 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0029_alter_userdata_client_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListyKlientow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True, verbose_name='Nazwa listy')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ac_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klima.acuser', verbose_name='Użytkownik tworzący')),
            ],
        ),
        migrations.AlterField(
            model_name='acuser',
            name='map_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='klima.listyklientow'),
        ),
        migrations.DeleteModel(
            name='ListaKlientow',
        ),
    ]
