# Generated by Django 5.1.6 on 2025-04-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0030_listyklientow_alter_acuser_map_list_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listyklientow',
            name='nazwa',
            field=models.CharField(max_length=100, verbose_name='Nazwa listy'),
        ),
    ]
