# Generated by Django 5.1.6 on 2025-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0031_alter_listyklientow_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='lista_klientow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
