# Generated by Django 5.1.6 on 2025-04-14 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0032_userdata_lista_klientow'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_monter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='klima.acuser'),
        ),
    ]
