# Generated by Django 5.1.6 on 2025-04-15 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0033_task_assigned_group_alter_task_assigned_monter'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie',
            name='pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_zadania', to='klima.acuser'),
        ),
    ]
