# Generated by Django 5.1.6 on 2025-04-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0034_zadanie_pracownik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zadanie',
            name='pracownik',
        ),
    ]
