# Generated by Django 5.1.6 on 2025-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0035_remove_zadanie_pracownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadanie',
            name='nazwa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
