# Generated by Django 5.1.6 on 2025-04-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0036_alter_zadanie_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadanie',
            name='grupa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
