# Generated by Django 5.1.6 on 2025-05-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0037_alter_zadanie_grupa'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie',
            name='notatki',
            field=models.TextField(blank=True, null=True),
        ),
    ]
