# Generated by Django 5.1.6 on 2025-07-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0038_zadanie_notatki'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspekcja',
            name='sposob_montazu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspekcja',
            name='uwagi_agregat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspekcja',
            name='uwagi_elektryka',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspekcja',
            name='uwagi_instalacja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspekcja',
            name='uwagi_ogolne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='miejsce_agregatu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='miejsce_urzadzen_wew',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='podlaczenie_elektryki',
            field=models.TextField(blank=True, null=True),
        ),
    ]
