# Generated by Django 5.1.6 on 2025-07-01 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0039_inspekcja_sposob_montazu_inspekcja_uwagi_agregat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['nazwa_oferty', '-wersja']},
        ),
        migrations.AddField(
            model_name='oferta',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='nazwa_oferty',
            field=models.CharField(blank=True, help_text='Nazwa grupy ofert', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wersja',
            field=models.IntegerField(default=1, help_text='Numer wersji oferty'),
        ),
    ]
