# Generated by Django 5.1.6 on 2025-07-01 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0040_alter_oferta_options_oferta_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serwis',
            name='montaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='przeglady', to='klima.montaz'),
        ),
        migrations.AddField(
            model_name='serwis',
            name='numer_przegladu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='termin_serwisu',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serwis',
            name='typ',
            field=models.CharField(choices=[('przeglad', 'Przegląd cykliczny'), ('serwis', 'Serwis indywidualny')], default='przeglad', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspekcja',
            name='photos',
            field=models.ManyToManyField(blank=True, to='klima.photo'),
        ),
    ]
