# Generated by Django 5.1.6 on 2025-07-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0041_serwis_montaz_serwis_numer_przegladu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Czy oferta jest szablonem'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='instalacja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='klima.instalacja'),
        ),
    ]
