# Generated by Django 5.1.6 on 2025-08-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0042_oferta_is_template_alter_oferta_instalacja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspekcja',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='inspekcja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_photos', to='klima.inspekcja'),
        ),
    ]
