# Generated by Django 5.1.6 on 2025-10-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0043_remove_inspekcja_photos_photo_inspekcja'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspekcja',
            name='miejsce_montazu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inspekcja',
            name='typ_urzadzenia_wewnetrznego',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zadanie',
            name='status',
            field=models.CharField(choices=[('wykonane', 'Wykonane'), ('niewykonane', 'Niewykonane'), ('Zaplanowane', 'Zaplanowane')], default='niewykonane', max_length=20),
        ),
    ]
