# Generated by Django 5.1.6 on 2025-10-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0044_add_inspection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='montaz',
            name='czyszczenie_filtrow_jedn_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='czyszczenie_obudowy_jedn_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='czyszczenie_obudowy_jedn_zew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='czyszczenie_tacy_skroplin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='czyszczenie_wymiennika_ciepla_jedn_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='czyszczenie_wymiennika_ciepla_jedn_zew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='diagnostyka_awarii_urzadzen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='kontrola_droznosci_odplywu_skroplin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='kontrola_poprawnosci_dzialania',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='kontrola_stanu_mocowania_agregatu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='kontrola_stanu_technicznego_jedn_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='kontrola_stanu_technicznego_jedn_zew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='kontrola_szczelnosci_instalacji',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='kontrola_temperatury_nawiewu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
