# Generated by Django 5.1.6 on 2025-10-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0045_montaz_czyszczenie_filtrow_jedn_wew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='selected_device_id',
            field=models.IntegerField(
                blank=True, help_text='ID wybranego urządzenia z oferty', null=True),
        ),
    ]
