# Generated by Django 5.1.6 on 2025-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0047_alter_photo_klient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='client_status',
            field=models.CharField(choices=[('0', 'Aktywny'), ('1', 'Nieaktywny')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='typ_klienta',
            field=models.CharField(choices=[('0', 'Aktywny'), ('1', 'Nieaktywny')], default='aktualny', max_length=20),
        ),
    ]
