# Generated by Django 5.1.6 on 2025-11-13 16:13

import django.db.models.deletion
from django.db import migrations, models


def create_table_if_not_exists(apps, schema_editor):
    """Tworzy tabelę tylko jeśli nie istnieje"""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Sprawdź czy tabela już istnieje
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'klima_invitation'
        """)
        table_exists = cursor.fetchone()[0] > 0

        if not table_exists:
            # Tabela nie istnieje - utwórz ją
            schema_editor.execute("""
                CREATE TABLE `klima_invitation` (
                    `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                    `email` varchar(254) NOT NULL,
                    `token` varchar(255) NOT NULL UNIQUE,
                    `created_at` datetime(6) NOT NULL,
                    `expires_at` datetime(6) NOT NULL,
                    `used` bool NOT NULL,
                    `used_at` datetime(6) NULL,
                    `client_id` bigint NOT NULL,
                    `created_by_id` bigint NOT NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
            """)
            schema_editor.execute("""
                ALTER TABLE `klima_invitation` 
                ADD CONSTRAINT `klima_invitation_client_id_fk` 
                FOREIGN KEY (`client_id`) REFERENCES `klima_acuser` (`id`)
            """)
            schema_editor.execute("""
                ALTER TABLE `klima_invitation` 
                ADD CONSTRAINT `klima_invitation_created_by_id_fk` 
                FOREIGN KEY (`created_by_id`) REFERENCES `klima_acuser` (`id`)
            """)


def reverse_create_table(apps, schema_editor):
    """Odwraca operację - usuwa tabelę jeśli istnieje"""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'klima_invitation'
        """)
        table_exists = cursor.fetchone()[0] > 0

        if table_exists:
            schema_editor.execute("DROP TABLE IF EXISTS `klima_invitation`")


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0048_alter_userdata_client_status_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Operacje na bazie danych - sprawdź czy tabela istnieje przed utworzeniem
                migrations.RunPython(
                    create_table_if_not_exists,
                    reverse_create_table,
                ),
            ],
            state_operations=[
                # Operacje na stanie Django - zawsze dodaj model do stanu
                migrations.CreateModel(
                    name='Invitation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True,
                         primary_key=True, serialize=False, verbose_name='ID')),
                        ('email', models.EmailField(max_length=254,
                         verbose_name='Email zaproszonego')),
                        ('token', models.CharField(max_length=255,
                         unique=True, verbose_name='Token zaproszenia')),
                        ('created_at', models.DateTimeField(
                            auto_now_add=True, verbose_name='Data utworzenia')),
                        ('expires_at', models.DateTimeField(
                            verbose_name='Data wygaśnięcia')),
                        ('used', models.BooleanField(
                            default=False, verbose_name='Czy użyte')),
                        ('used_at', models.DateTimeField(
                            blank=True, null=True, verbose_name='Data użycia')),
                        ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                         related_name='invitations', to='klima.acuser', verbose_name='Klient powiązany z zaproszeniem')),
                        ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                         related_name='sent_invitations', to='klima.acuser', verbose_name='Użytkownik wysyłający zaproszenie')),
                    ],
                    options={
                        'verbose_name': 'Zaproszenie',
                        'verbose_name_plural': 'Zaproszenia',
                    },
                ),
            ],
        ),
    ]
