# Generated by Django 5.1.6 on 2025-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0049_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuser',
            name='has_account',
            field=models.BooleanField(default=False, verbose_name='Czy ma konto w aplikacji'),
        ),
        migrations.AlterField(
            model_name='acuser',
            name='hash_value',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False, help_text='Czy oferta jest szablonem'),
        ),
        migrations.AddIndex(
            model_name='acuser',
            index=models.Index(fields=['hash_value'], name='acuser_hash_value_idx'),
        ),
        migrations.AddIndex(
            model_name='acuser',
            index=models.Index(fields=['email'], name='acuser_email_idx'),
        ),
        migrations.AddIndex(
            model_name='instalacja',
            index=models.Index(fields=['klient'], name='instalacja_klient_idx'),
        ),
        migrations.AddIndex(
            model_name='instalacja',
            index=models.Index(fields=['owner'], name='instalacja_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['instalacja'], name='oferta_instalacja_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['creator'], name='oferta_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['is_template'], name='oferta_is_template_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['instalacja', 'is_template'], name='oferta_instalacja_template_idx'),
        ),
    ]
