# Generated by Django 4.2.2 on 2025-12-09 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0050_acuser_has_account_alter_acuser_hash_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja')),
                ('participant_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p1', to='klima.acuser', verbose_name='Uczestnik 1 (Admin/Monter)')),
                ('participant_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p2', to='klima.acuser', verbose_name='Uczestnik 2 (Klient)')),
            ],
            options={
                'verbose_name': 'Konwersacja',
                'verbose_name_plural': 'Konwersacje',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść wiadomości')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data wysłania')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Czy przeczytana')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Data przeczytania')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='klima.conversation', verbose_name='Konwersacja')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='klima.acuser', verbose_name='Nadawca')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', '-created_at'], name='msg_conv_created_idx'), models.Index(fields=['conversation', 'is_read'], name='msg_conv_read_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_1', 'participant_2'], name='conv_participants_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='conv_updated_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('participant_1', 'participant_2')},
        ),
    ]
