# Generated by Django 6.0 on 2025-12-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0051_conversation_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Unikalny identyfikator urządzenia', max_length=255, unique=True)),
                ('license_type', models.CharField(choices=[('demo', 'Demo - 5 dni'), ('blocked', 'Zablokowane'), ('full', 'Pełna licencja')], default='demo', help_text='Typ aktualnej licencji', max_length=10)),
                ('first_launch_date', models.DateTimeField(blank=True, help_text='Data pierwszego uruchomienia aplikacji', null=True)),
                ('demo_expiry_date', models.DateTimeField(blank=True, help_text='Data wygaśnięcia okresu demo', null=True)),
                ('activation_date', models.DateTimeField(blank=True, help_text='Data aktywacji pełnej licencji', null=True)),
                ('device_model', models.CharField(blank=True, help_text='Model urządzenia np. Samsung Galaxy S21', max_length=100)),
                ('device_os', models.CharField(blank=True, help_text='System operacyjny np. Android 13', max_length=50)),
                ('app_version', models.CharField(blank=True, help_text='Wersja aplikacji', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data utworzenia rekordu')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data ostatniej aktualizacji')),
                ('last_check', models.DateTimeField(blank=True, help_text='Data ostatniego sprawdzenia licencji przez aplikację', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notatki administracyjne - powód blokady, informacje o kliencie, etc.')),
                ('check_count', models.IntegerField(default=0, help_text='Liczba sprawdzeń licencji')),
                ('ac_user', models.ForeignKey(blank=True, help_text='Użytkownik powiązany z tym urządzeniem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_licenses', to='klima.acuser')),
            ],
            options={
                'verbose_name': 'Licencja urządzenia',
                'verbose_name_plural': 'Licencje urządzeń',
                'db_table': 'device_licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLicenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REGISTERED', 'Zarejestrowane'), ('CHECKED', 'Sprawdzone'), ('ACTIVATED', 'Aktywowane'), ('BLOCKED', 'Zablokowane'), ('AUTO_BLOCKED', 'Auto-zablokowane'), ('EXTENDED', 'Przedłużone demo')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('license_type_snapshot', models.CharField(blank=True, max_length=10)),
                ('device_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='klima.devicelicense')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='klima.acuser')),
            ],
            options={
                'verbose_name': 'Log licencji',
                'verbose_name_plural': 'Logi licencji',
                'db_table': 'device_license_logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devicelicense',
            index=models.Index(fields=['device_id'], name='device_id_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelicense',
            index=models.Index(fields=['license_type'], name='license_type_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelicense',
            index=models.Index(fields=['demo_expiry_date'], name='demo_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelicense',
            index=models.Index(fields=['ac_user'], name='license_ac_user_idx'),
        ),
    ]
