# Generated by Django 6.0 on 2025-12-15 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0052_devicelicense_devicelicenselog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_full_license', models.BooleanField(default=False, help_text='Czy automatycznie nadawać pełną licencję nowym urządzeniom (zamiast demo)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Kto ostatnio zmienił ustawienia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='klima.acuser')),
            ],
            options={
                'verbose_name': 'Ustawienia Licencji',
                'verbose_name_plural': 'Ustawienia Licencji',
                'db_table': 'license_settings',
            },
        ),
    ]
