# Generated by Django 4.2.2 on 2025-12-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0053_licensesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='montaz_status',
            field=models.CharField(choices=[('none', 'Brak propozycji'), ('pending', 'Oczekuje na akceptację'), ('confirmed', 'Zatwierdzony'), ('rejected', 'Odrzucony')], default='none', help_text='Status rezerwacji terminu montażu', max_length=20),
        ),
        migrations.AddField(
            model_name='oferta',
            name='montaz_zadanie',
            field=models.ForeignKey(blank=True, help_text='Powiązane zadanie montażu w kalendarzu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta_montaz', to='klima.zadanie'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='proposed_montaz_date',
            field=models.DateField(blank=True, help_text='Data montażu zaproponowana przez klienta', null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='proposed_montaz_time',
            field=models.TimeField(blank=True, help_text='Godzina montażu zaproponowana przez klienta', null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Powód odrzucenia terminu przez montera', null=True),
        ),
    ]
