# Generated by Django 4.2.2 on 2026-01-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0054_oferta_montaz_status_oferta_montaz_zadanie_and_more'),
        ('klima', '0055_pushnotificationtoken_notification'),
    ]

    operations = [
    ]
