# Generated by Django 6.0.1 on 2026-01-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0056_merge_20260103_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacja',
            name='kod_pocztowy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instalacja',
            name='miasto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instalacja',
            name='mieszkanie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instalacja',
            name='numer_domu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instalacja',
            name='ulica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
