# Generated by Django 6.0.1 on 2026-01-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0057_instalacja_kod_pocztowy_instalacja_miasto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='montaz',
            name='dlugosc_instalacji',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='gwarancja_photo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='montaz',
            name='devicePower',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
