# Generated by Django 6.0.1 on 2026-01-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klima', '0058_montaz_dlugosc_instalacji_montaz_gwarancja_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serwis',
            name='kontrola_stanu_jedn_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='kontrola_stanu_jedn_zew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='kontrola_stanu_mocowania_agregatu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='czyszczenie_filtrow_jedn_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='czyszczenie_wymiennika_ciepla_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='czyszczenie_obudowy_jedn_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='czyszczenie_tacy_skroplin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='kontrola_droznosci_skroplin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='czyszczenie_obudowy_jedn_zew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='czyszczenie_wymiennika_ciepla_zew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='kontrola_szczelnosci',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='kontrola_poprawnosci_dzialania',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='kontrola_temperatury_nawiewu_wew',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serwis',
            name='diagnostyka_awari',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
